/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Root */
    get: operations['read_root__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/absences': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Avisar ausência numa rota
     * @description Passageiro (ou guardian em nome de dependente) registra o aviso de ausência numa data específica da rota. Erros: 404 se a rota não existir; 403 se o usuário não tiver vínculo ativo; 409 se já houver ausência pro mesmo RP na data ou se a data for inválida.
     */
    post: operations['create_absence_absences_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations['login_auth_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations['logout_auth_logout_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/password/forgot': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Forgot Password */
    post: operations['forgot_password_auth_password_forgot_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/password/reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reset Password */
    post: operations['reset_password_auth_password_reset_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh */
    post: operations['refresh_auth_refresh_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dependents/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listar dependentes do usuário
     * @description Retorna todos os dependentes cadastrados pelo usuário logado.
     */
    get: operations['list_dependents_dependents__get'];
    put?: never;
    /**
     * Adicionar dependente
     * @description Permite que um passageiro ou responsável adicione um dependente ao seu perfil.
     */
    post: operations['create_dependent_dependents__post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dependents/{dependent_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Buscar dependente por ID
     * @description Retorna um dependente específico do usuário logado.
     */
    get: operations['get_dependent_dependents__dependent_id__get'];
    /**
     * Atualizar dependente
     * @description Atualiza os dados de um dependente do usuário logado.
     */
    put: operations['update_dependent_dependents__dependent_id__put'];
    post?: never;
    /**
     * Excluir dependente
     * @description Remove um dependente do perfil do usuário logado.
     */
    delete: operations['delete_dependent_dependents__dependent_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health Check */
    get: operations['health_check_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/metrics/reports': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Relatório agregado de viagens do motorista
     * @description Retorna distância (km), duração (min), passageiros transportados e viagens realizadas do motorista logado no período selecionado (day/week/month) e intervalo de datas.
     */
    get: operations['get_reports_metrics_reports_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/routes/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listar todas as rotas do motorista
     * @description Retorna todas as rotas cadastradas pelo motorista, independente de status.
     */
    get: operations['list_routes_routes__get'];
    put?: never;
    /**
     * Criar uma nova rota
     * @description Cria uma rota para o motorista com origem, destino, horário e recorrência. Gera automaticamente o código de convite e salva com status inativa.
     */
    post: operations['create_route_routes__post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/routes/invite/{invite_code}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Resumo de rota por código de convite
     * @description Retorna o resumo público da rota identificada pelo invite_code, para que o passageiro decida se solicita entrada. Inclui accepted_count (quantidade de passageiros já aceitos) mas não expõe invite_code, status nem stops.
     */
    get: operations['get_route_by_invite_code_routes_invite__invite_code__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/routes/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listar minhas rotas (home do passageiro)
     * @description Retorna todos os vínculos ativos (pending + accepted) do usuário autenticado, incluindo vínculos em que ele é guardian de um dependente. Ordenado por joined_at desc. Usado pela home do passageiro.
     */
    get: operations['list_my_routes_routes_me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/routes/{route_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Detalhe de uma rota
     * @description Retorna os dados completos de uma rota, incluindo endereços de origem e destino.
     */
    get: operations['get_route_routes__route_id__get'];
    /**
     * Editar rota
     * @description Atualiza uma rota existente do motorista. Permite alteração parcial (name, route_type, origin, destination, expected_time, recurrence). Rotas com status='em_andamento' não podem ser editadas.
     */
    put: operations['update_route_routes__route_id__put'];
    post?: never;
    /**
     * Excluir rota
     * @description Exclui uma rota do motorista. Apenas o motorista dono pode excluir. Rotas com status='em_andamento' não podem ser excluídas. Passageiros ativos (pending/accepted) são notificados antes da exclusão. A remoção é em cascata: route_passangers, schedules e stops associadas também são apagados.
     */
    delete: operations['delete_route_routes__route_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/routes/{route_id}/absences': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Ausências da rota numa data
     * @description Retorna os passageiros que avisaram ausência na data informada. Usado pelo motorista para separar stops presentes de ausentes na próxima partida. date padrão: hoje (UTC). 403 se não for dono da rota. 404 se a rota não existir.
     */
    get: operations['list_route_absences_routes__route_id__absences_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/routes/{route_id}/invite-code/regenerate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Revogar e gerar novo código de convite
     * @description Invalida o código de convite atual e gera um novo. Apenas o motorista dono da rota pode realizar esta ação.
     */
    post: operations['regenerate_invite_code_routes__route_id__invite_code_regenerate_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/routes/{route_id}/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Detalhe da rota para o passageiro
     * @description Retorna o detalhe completo da rota do ponto de vista do passageiro autenticado. Aceita dependent_id opcional quando guardian está vendo em nome do dependente. Não expõe invite_code/max_passengers/driver_id. Erros: 404 se a rota não existir, 403 se o usuário não tiver vínculo ativo com a rota.
     */
    get: operations['get_my_route_detail_routes__route_id__me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/routes/{route_id}/passangers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listar passageiros/solicitações da rota
     * @description Lista vínculos de passageiros da rota. Aceita filtro opcional por status (pending, accepted, rejected). Sem filtro retorna todos.
     */
    get: operations['list_passangers_routes__route_id__passangers_get'];
    put?: never;
    /**
     * Solicitar entrada em rota
     * @description Passageiro (ou guardian em nome de dependente) solicita entrada na rota informando schedules (dias + endereço de embarque). Cria vínculo pending.
     */
    post: operations['join_route_routes__route_id__passangers_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/routes/{route_id}/passangers/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Sair de uma rota
     * @description Passageiro sai da rota. Aceita dependent_id opcional quando guardian está saindo em nome do dependente. Bloqueado se rota está em andamento.
     */
    delete: operations['leave_route_routes__route_id__passangers_me_delete'];
    options?: never;
    head?: never;
    /**
     * Atualizar schedules de participação
     * @description Substitui completamente os schedules atuais do passageiro pelos fornecidos. Aceita dependent_id opcional para guardian em nome de dep.
     */
    patch: operations['update_schedules_routes__route_id__passangers_me_patch'];
    trace?: never;
  };
  '/routes/{route_id}/passangers/{rp_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Remover passageiro da rota
     * @description Remove um passageiro da rota. Bloqueado se a rota estiver em andamento.
     */
    delete: operations['remove_passanger_routes__route_id__passangers__rp_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/routes/{route_id}/passangers/{rp_id}/accept': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Aceitar solicitação de passageiro
     * @description Aprova uma solicitação pending. Valida ownership, bloqueio de rota em andamento e capacidade máxima do veículo.
     */
    post: operations['accept_request_routes__route_id__passangers__rp_id__accept_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/routes/{route_id}/passangers/{rp_id}/reject': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Recusar solicitação de passageiro
     * @description Recusa uma solicitação pending. Valida ownership e bloqueio de rota em andamento. Não valida capacidade.
     */
    post: operations['reject_request_routes__route_id__passangers__rp_id__reject_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/routes/{route_id}/trips': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Motorista inicia a execução da rota */
    post: operations['start_trip_routes__route_id__trips_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/routes/{route_id}/trips/current': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Passageiro consulta viagem em andamento da sua rota
     * @description Retorna o trip_id e status da viagem iniciada na rota, se existir. Qualquer usuário com vínculo ativo (pending ou accepted) pode consultar — não é restrito ao motorista. Aceita dependent_id opcional para guardian consultando em nome do dependente. Retorna null quando não há viagem em andamento. 404 se a rota não existir. 403 se o usuário não tiver vínculo ativo.
     */
    get: operations['get_current_trip_for_passanger_routes__route_id__trips_current_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/trips/{trip_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Detalhes da viagem em andamento (motorista) */
    get: operations['get_trip_trips__trip_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/trips/{trip_id}/finish': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Motorista finaliza a viagem */
    post: operations['finish_trip_trips__trip_id__finish_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/trips/{trip_id}/next-stop': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Próxima parada pendente + info do passageiro */
    get: operations['get_next_stop_trips__trip_id__next_stop_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/trips/{trip_id}/passangers/{trip_passanger_id}/absent': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Motorista marca passageiro como não embarcado */
    post: operations['mark_passanger_absent_trips__trip_id__passangers__trip_passanger_id__absent_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/trips/{trip_id}/passangers/{trip_passanger_id}/alight': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Motorista registra desembarque manual de um passageiro */
    post: operations['alight_passanger_trips__trip_id__passangers__trip_passanger_id__alight_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/trips/{trip_id}/passangers/{trip_passanger_id}/board': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Motorista confirma embarque de um passageiro */
    post: operations['board_passanger_trips__trip_id__passangers__trip_passanger_id__board_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/trips/{trip_id}/stops/{stop_id}/skip': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Motorista pula uma parada (marca passageiros como ausente) */
    post: operations['skip_stop_trips__trip_id__stops__stop_id__skip_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/uploads/photo': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Upload de foto de perfil
     * @description Recebe uma imagem, faz o upload para o serviço de armazenamento e retorna a URL pública.
     */
    post: operations['upload_photo_uploads_photo_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listar todos os usuários
     * @description Retorna a lista de todos os usuários cadastrados.
     */
    get: operations['list_users_users__get'];
    put?: never;
    /**
     * Registrar um novo usuário
     * @description Cria um usuário no banco e retorna os dados sem a senha.
     */
    post: operations['register_user_users__post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login intermediário (email + senha)
     * @description Valida e-mail e senha. Retorna o UserResponse em sucesso. 404 quando o e-mail não está cadastrado, 401 quando a senha está incorreta. Sem emissão de token — autenticação completa será adicionada em US futura.
     */
    post: operations['login_user_users_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Me */
    get: operations['get_me_users_me_get'];
    put?: never;
    post?: never;
    /** Delete My Account */
    delete: operations['delete_my_account_users_me_delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/me/push-token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Registrar FCM push token do dispositivo
     * @description Associa o token FCM do dispositivo ao usuário autenticado. Usado pelo app mobile logo após o login para habilitar notificações push. 404 se o usuário não existir.
     */
    post: operations['register_push_token_users_me_push_token_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/me/send-test-notification': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Enviar notificação de teste para o usuário logado
     * @description Helper de teste: envia um push para o push_token do usuário autenticado, para validar o pipeline FCM ponta a ponta sem disparar um evento real. Body é opcional (title/body têm default). 404 se o usuário não existir, 400 se não houver push_token registrado, 502 se o FCM rejeitar o envio.
     */
    post: operations['send_test_notification_users_me_send_test_notification_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{user_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Buscar usuário por ID
     * @description Retorna os dados de um usuário específico pelo seu ID.
     */
    get: operations['get_user_users__user_id__get'];
    /**
     * Atualizar usuário
     * @description Atualiza os campos de um usuário existente.
     */
    put: operations['update_user_users__user_id__put'];
    post?: never;
    /**
     * Excluir usuário (deprecated)
     * @deprecated
     * @description Remove a conta do usuário e todos os dados associados em cascata. Este endpoint está depreciado em favor de DELETE /users/me.
     */
    delete: operations['delete_user_users__user_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vehicles/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listar veículos do usuário
     * @description Retorna todos os veículos cadastrados pelo motorista logado.
     */
    get: operations['list_vehicles_vehicles__get'];
    put?: never;
    /**
     * Adicionar veículo
     * @description Permite que um motorista adicione um veículo ao seu perfil.
     */
    post: operations['create_vehicle_vehicles__post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vehicles/{vehicle_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Buscar veículo por ID
     * @description Retorna um veículo específico do motorista logado.
     */
    get: operations['get_vehicle_vehicles__vehicle_id__get'];
    /**
     * Atualizar veículo
     * @description Atualiza os dados de um veículo do motorista logado.
     */
    put: operations['update_vehicle_vehicles__vehicle_id__put'];
    post?: never;
    /**
     * Excluir veículo
     * @description Remove um veículo do perfil do motorista logado.
     */
    delete: operations['delete_vehicle_vehicles__vehicle_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AbsenceResponse
     * @description Representação de uma ausência persistida.
     */
    AbsenceResponse: {
      /**
       * Absence Date
       * Format: date-time
       */
      absence_date: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Reason */
      reason?: string | null;
      /**
       * Route Passanger Id
       * Format: uuid
       */
      route_passanger_id: string;
      /** Trip Id */
      trip_id?: string | null;
    };
    /** AddressCreate */
    AddressCreate: {
      /** City */
      city: string;
      /** Label */
      label: string;
      /** Neighborhood */
      neighborhood: string;
      /** Number */
      number: string;
      /** State */
      state: string;
      /** Street */
      street: string;
      /** Zip */
      zip: string;
    };
    /** AddressResponse */
    AddressResponse: {
      /** City */
      city: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Label */
      label: string;
      /** Latitude */
      latitude?: number | null;
      /** Longitude */
      longitude?: number | null;
      /** Neighborhood */
      neighborhood: string;
      /** Number */
      number: string;
      /** State */
      state: string;
      /** Street */
      street: string;
      /** Zip */
      zip: string;
    };
    /** Body_upload_photo_uploads_photo_post */
    Body_upload_photo_uploads_photo_post: {
      /** File */
      file: string;
    };
    /**
     * CreateAbsenceRequest
     * @description Payload enviado pelo passageiro (ou guardian) pra avisar ausência numa rota.
     */
    CreateAbsenceRequest: {
      /**
       * Absence Date
       * Format: date
       */
      absence_date: string;
      /** Dependent Id */
      dependent_id?: string | null;
      /** Reason */
      reason?: string | null;
      /**
       * Route Id
       * Format: uuid
       */
      route_id: string;
    };
    /**
     * CurrentTripResponse
     * @description Resposta mínima exposta ao passageiro para acompanhamento da viagem.
     *
     *     Retornada por GET /routes/{route_id}/trips/current.
     *     Permite ao app do passageiro descobrir o trip_id e conectar ao Socket.IO,
     *     além de exibir as informações básicas do motorista e do veículo.
     *     Retorna None (204/null) quando não há viagem em andamento na rota.
     *
     *     Fields:
     *     - trip_id: UUID — identificador da viagem em andamento
     *     - status: str   — sempre "iniciada" enquanto em andamento
     *     - started_at: datetime | None — horário de início da viagem
     *     - driver_name: str — nome do motorista da rota
     *     - driver_photo_url: str | None — foto do motorista (FE usa no card de info)
     *     - vehicle_plate: str | None — placa do veículo da viagem
     */
    CurrentTripResponse: {
      /** Driver Name */
      driver_name: string;
      /** Driver Photo Url */
      driver_photo_url?: string | null;
      /** Started At */
      started_at?: string | null;
      /** Status */
      status: string;
      /**
       * Trip Id
       * Format: uuid
       */
      trip_id: string;
      /** Vehicle Plate */
      vehicle_plate?: string | null;
    };
    /** DeleteAccountRequest */
    DeleteAccountRequest: {
      /**
       * Confirm
       * @description Precisa ser true para excluir a conta.
       * @default false
       */
      confirm: boolean;
    };
    /** DependentCreate */
    DependentCreate: {
      /** Name */
      name: string;
    };
    /** DependentResponse */
    DependentResponse: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Guardian Id
       * Format: uuid
       */
      guardian_id: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
    };
    /** DependentUpdate */
    DependentUpdate: {
      /** Name */
      name?: string | null;
    };
    /**
     * FinishTripRequest
     * @description Payload enviado pelo motorista ao finalizar a viagem.
     *
     *     Fields esperados:
     *     - total_km: float | None — distância total percorrida (opcional)
     */
    FinishTripRequest: {
      /**
       * Total Km
       * @description Distância total percorrida
       */
      total_km?: number | null;
    };
    /** ForgotPasswordRequest */
    ForgotPasswordRequest: {
      /**
       * Email
       * Format: email
       * @example john.doe@example.com
       */
      email: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /**
     * JoinRouteRequest
     * @description Payload para um passageiro solicitar entrada em uma rota.
     *
     *     O campo `address` define o endereço de embarque que será criado inline pelo
     *     backend — o frontend não precisa fazer um POST /addresses separado.
     *     O mesmo endereço é usado como pickup_address em todos os dias da recorrência.
     */
    JoinRouteRequest: {
      /** @description Endereço de embarque do passageiro (criado inline) */
      address: components['schemas']['AddressCreate'];
      /**
       * Dependent Id
       * @description UUID do dependente, se guardian solicita em seu nome
       */
      dependent_id?: string | null;
      /**
       * Schedules
       * @description Pelo menos um dia de agendamento
       */
      schedules: components['schemas']['JoinRouteScheduleRequest'][];
    };
    /**
     * JoinRouteScheduleRequest
     * @description Item de agendamento no payload de entrada na rota.
     *
     *     O endereço de embarque é informado uma única vez em JoinRouteRequest.address
     *     e é reutilizado em todos os dias — por isso este DTO não carrega address_id.
     */
    JoinRouteScheduleRequest: {
      /**
       * Day Of Week
       * @description Dia da semana em inglês
       * @enum {string}
       */
      day_of_week:
        | 'monday'
        | 'tuesday'
        | 'wednesday'
        | 'thursday'
        | 'friday'
        | 'saturday'
        | 'sunday';
    };
    /** LoginRequest */
    LoginRequest: {
      /**
       * Email
       * Format: email
       * @example john.doe@example.com
       */
      email: string;
      /**
       * Password
       * @example senha_segura123
       */
      password: string;
    };
    /**
     * LoginResponse
     * @description Retornado por POST /auth/login e /auth/refresh: tokens + dados do usuário.
     *
     *     `refresh_token` é populado quando o fluxo de refresh está ativo (US17-TK09).
     */
    LoginResponse: {
      /** Access Token */
      access_token: string;
      /** Refresh Token */
      refresh_token?: string | null;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
      user: components['schemas']['UserResponse'];
    };
    /** MetricsReportResponse */
    MetricsReportResponse: {
      /**
       * Distance
       * @default 0
       */
      distance: number;
      /**
       * Duration
       * @default 0
       */
      duration: number;
      /**
       * End Date
       * Format: date
       */
      end_date: string;
      /**
       * Passengers
       * @default 0
       */
      passengers: number;
      period: components['schemas']['ReportPeriod'];
      /**
       * Start Date
       * Format: date
       */
      start_date: string;
      /**
       * Trips
       * @default 0
       */
      trips: number;
    };
    /**
     * PassangerRouteDetailResponse
     * @description Detalhe completo da rota do ponto de vista do passageiro (tela 2.3).
     *
     *     Projeção passageiro-facing — NÃO expõe invite_code, max_passengers nem
     *     driver_id. Retornada por GET /routes/{route_id}/me.
     */
    PassangerRouteDetailResponse: {
      /** Current Trip Id */
      current_trip_id?: string | null;
      /** Dependent Id */
      dependent_id?: string | null;
      /** Dependent Name */
      dependent_name?: string | null;
      destination_address: components['schemas']['AddressResponse'];
      /** Driver Name */
      driver_name: string;
      /** Driver Phone */
      driver_phone: string;
      /** Driver Plate */
      driver_plate?: string | null;
      /**
       * Estimated Duration Min
       * @description Duração estimada planejada origem→stops→destino em minutos
       */
      estimated_duration_min?: number | null;
      /**
       * Expected Time
       * Format: time
       */
      expected_time: string;
      /** Membership Status */
      membership_status: string;
      my_pickup_address: components['schemas']['AddressResponse'];
      /** My Schedules */
      my_schedules: components['schemas']['RoutePassangerScheduleResponse'][];
      /** Name */
      name: string;
      origin_address: components['schemas']['AddressResponse'];
      /** Recurrence */
      recurrence: string[];
      /**
       * Route Id
       * Format: uuid
       */
      route_id: string;
      /** Route Type */
      route_type: string;
      /** Status */
      status: string;
      /** Stops */
      stops: components['schemas']['StopResponse'][];
      /**
       * Total Distance Km
       * @description Distância total planejada origem→stops→destino em km
       */
      total_distance_km?: number | null;
    };
    /**
     * PassangerRouteResponse
     * @description Item da lista 'Minhas Rotas' da home do passageiro.
     */
    PassangerRouteResponse: {
      /** Dependent Name */
      dependent_name?: string | null;
      /** Destination Label */
      destination_label: string;
      /** Destination Latitude */
      destination_latitude?: number | null;
      /** Destination Longitude */
      destination_longitude?: number | null;
      /** Driver Name */
      driver_name: string;
      /** Driver Phone */
      driver_phone: string;
      /**
       * Estimated Duration Min
       * @description Duração estimada planejada origem→stops→destino em minutos
       */
      estimated_duration_min?: number | null;
      /**
       * Expected Time
       * Format: time
       */
      expected_time: string;
      /**
       * Joined At
       * Format: date-time
       */
      joined_at: string;
      /** Membership Status */
      membership_status: string;
      /** Origin Label */
      origin_label: string;
      /** Origin Latitude */
      origin_latitude?: number | null;
      /** Origin Longitude */
      origin_longitude?: number | null;
      /** Recurrence */
      recurrence: string[];
      /**
       * Route Id
       * Format: uuid
       */
      route_id: string;
      /** Route Name */
      route_name: string;
      /** Schedules */
      schedules: components['schemas']['RoutePassangerScheduleResponse'][];
      /** Status */
      status: string;
      /**
       * Total Distance Km
       * @description Distância total planejada origem→stops→destino em km
       */
      total_distance_km?: number | null;
    };
    /** RefreshRequest */
    RefreshRequest: {
      /** Refresh Token */
      refresh_token: string;
    };
    /**
     * RegisterPushTokenRequest
     * @description Payload para registrar o FCM push token do dispositivo do usuário.
     *
     *     Fields:
     *     - token: str — token FCM gerado pelo Firebase SDK no app mobile
     */
    RegisterPushTokenRequest: {
      /**
       * Token
       * @description FCM push token do dispositivo
       */
      token: string;
    };
    /**
     * ReportPeriod
     * @description Granularidade do relatório selecionada nas abas Dia / Semana / Mês.
     * @enum {string}
     */
    ReportPeriod: 'day' | 'week' | 'month';
    /**
     * ResetPasswordConfirm
     * @description A nova senha respeita as mesmas regras do cadastro (US16-TK01).
     */
    ResetPasswordConfirm: {
      /** New Password */
      new_password: string;
      /** Token */
      token: string;
    };
    /**
     * RouteAbsenceResponse
     * @description Ausência de um passageiro numa rota, vista pelo motorista.
     */
    RouteAbsenceResponse: {
      /**
       * Absence Date
       * Format: date-time
       */
      absence_date: string;
      /** Dependent Id */
      dependent_id: string | null;
      /** Dependent Name */
      dependent_name: string | null;
      /** Reason */
      reason: string | null;
      /**
       * Route Passanger Id
       * Format: uuid
       */
      route_passanger_id: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** User Name */
      user_name: string;
    };
    /** RouteCreate */
    RouteCreate: {
      destination: components['schemas']['AddressCreate'];
      /**
       * Expected Time
       * Format: time
       */
      expected_time: string;
      /** Name */
      name: string;
      origin: components['schemas']['AddressCreate'];
      /** Recurrence */
      recurrence: string;
      /** Route Type */
      route_type: string;
    };
    /**
     * RouteInviteSummaryResponse
     * @description Resumo da rota retornado ao passageiro durante a busca por invite_code.
     *
     *     Expõe apenas o que o passageiro precisa para decidir se quer solicitar
     *     entrada: dados básicos da rota + capacidade e quantos já foram aceitos.
     *     Não expõe lista de passageiros nem stops.
     */
    RouteInviteSummaryResponse: {
      /**
       * Accepted Count
       * @description Contagem de passageiros aceitos (injetado pelo service)
       */
      accepted_count: number;
      destination_address: components['schemas']['AddressResponse'];
      /**
       * Expected Time
       * Format: time
       */
      expected_time: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Max Passengers */
      max_passengers: number;
      /** Name */
      name: string;
      origin_address: components['schemas']['AddressResponse'];
      /** Recurrence */
      recurrence: string;
      /** Route Type */
      route_type: string;
    };
    /** RoutePassangerResponse */
    RoutePassangerResponse: {
      /** Dependent Id */
      dependent_id?: string | null;
      /** Dependent Name */
      dependent_name?: string | null;
      /** Guardian Name */
      guardian_name?: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Joined At */
      joined_at?: string | null;
      /** Photo Url */
      photo_url?: string | null;
      /**
       * Pickup Address Id
       * Format: uuid
       */
      pickup_address_id: string;
      /**
       * Requested At
       * Format: date-time
       */
      requested_at: string;
      /**
       * Route Id
       * Format: uuid
       */
      route_id: string;
      /** Status */
      status: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** User Name */
      user_name: string;
      /** User Phone */
      user_phone: string;
    };
    /**
     * RoutePassangerScheduleRequest
     * @description Item de agendamento enviado pelo passageiro: dia + endereço de embarque.
     *
     *     Usado pelo UpdateSchedulesRequest (PATCH schedules).
     */
    RoutePassangerScheduleRequest: {
      /**
       * Address Id
       * Format: uuid
       * @description Endereço de embarque neste dia
       */
      address_id: string;
      /**
       * Day Of Week
       * @description Dia da semana em inglês
       * @enum {string}
       */
      day_of_week:
        | 'monday'
        | 'tuesday'
        | 'wednesday'
        | 'thursday'
        | 'friday'
        | 'saturday'
        | 'sunday';
    };
    /**
     * RoutePassangerScheduleResponse
     * @description Representação de um agendamento persistido.
     */
    RoutePassangerScheduleResponse: {
      /**
       * Address Id
       * Format: uuid
       */
      address_id: string;
      /** Day Of Week */
      day_of_week: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
    };
    /** RouteResponse */
    RouteResponse: {
      /**
       * Accepted Count
       * @description Quantidade de passageiros aceitos na rota
       * @default 0
       */
      accepted_count: number;
      /**
       * Active Trip Id
       * @description ID da trip em andamento para esta rota, null se não houver
       */
      active_trip_id?: string | null;
      destination_address: components['schemas']['AddressResponse'];
      /**
       * Estimated Duration Min
       * @description Duração estimada planejada origem→stops→destino em minutos
       */
      estimated_duration_min?: number | null;
      /**
       * Expected Time
       * Format: time
       */
      expected_time: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Invite Code */
      invite_code: string;
      /** Max Passengers */
      max_passengers: number;
      /** Name */
      name: string;
      origin_address: components['schemas']['AddressResponse'];
      /** Recurrence */
      recurrence: string;
      /** Route Type */
      route_type: string;
      /** Status */
      status: string;
      /** Stops */
      stops?: components['schemas']['StopResponse'][];
      /**
       * Total Distance Km
       * @description Distância total planejada origem→stops→destino em km
       */
      total_distance_km?: number | null;
    };
    /**
     * RouteUpdate
     * @description DTO de atualização parcial de rota. Todos os campos são opcionais.
     *
     *     Regras:
     *     - route_type: "outbound" ou "inbound"
     *     - recurrence: mesma validação de RouteCreate (dias válidos, sem duplicatas, >=1 dia)
     *     - origin != destination quando AMBOS estão presentes
     */
    RouteUpdate: {
      destination?: components['schemas']['AddressCreate'] | null;
      /** Expected Time */
      expected_time?: string | null;
      /** Name */
      name?: string | null;
      origin?: components['schemas']['AddressCreate'] | null;
      /** Recurrence */
      recurrence?: string | null;
      /** Route Type */
      route_type?: string | null;
    };
    /**
     * SendTestNotificationRequest
     * @description Payload opcional para customizar a notificação de teste.
     *
     *     Ambos os campos têm default, então um POST com body vazio já funciona.
     */
    SendTestNotificationRequest: {
      /**
       * Body
       * @default Se você está vendo isso, o pipeline de push está funcionando.
       */
      body: string;
      /**
       * Title
       * @default Teste de push VanGo
       */
      title: string;
    };
    /**
     * SendTestNotificationResponse
     * @description Resultado do envio de teste.
     */
    SendTestNotificationResponse: {
      /** Detail */
      detail: string;
      /** Message Id */
      message_id?: string | null;
      /** Success */
      success: boolean;
    };
    /**
     * StartTripRequest
     * @description Payload enviado pelo motorista para iniciar a viagem.
     *
     *     Fields esperados:
     *     - vehicle_id: UUID — veículo que vai executar a viagem (precisa pertencer
     *       ao motorista dono da rota)
     *     - trip_date: datetime | None — data/hora da viagem. Default: now()
     */
    StartTripRequest: {
      /**
       * Trip Date
       * @description Data/hora da viagem
       */
      trip_date?: string | null;
      /**
       * Vehicle Id
       * Format: uuid
       * @description Veículo que vai executar a viagem
       */
      vehicle_id: string;
    };
    /** StopResponse */
    StopResponse: {
      address: components['schemas']['AddressResponse'];
      /**
       * Address Id
       * Format: uuid
       */
      address_id: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Order Index */
      order_index: number;
      /**
       * Route Id
       * Format: uuid
       */
      route_id: string;
      /**
       * Route Passanger Id
       * Format: uuid
       */
      route_passanger_id: string;
      /** Type */
      type: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * TripNextStopResponse
     * @description Próxima parada da viagem em andamento.
     *
     *     Fields esperados:
     *     - stop_id: UUID
     *     - order_index: int
     *     - address_label: str
     *     - passanger_name: str
     *     - passanger_phone: str          — telefone pra contato direto (US13)
     *     - trip_passanger_id: UUID
     *     - trip_passanger_status: str    — "pendente" | "presente" | "ausente"
     */
    TripNextStopResponse: {
      /** Address Label */
      address_label: string;
      /** Latitude */
      latitude?: number | null;
      /** Longitude */
      longitude?: number | null;
      /** Order Index */
      order_index: number;
      /** Passanger Name */
      passanger_name: string;
      /** Passanger Phone */
      passanger_phone: string;
      /**
       * Stop Id
       * Format: uuid
       */
      stop_id: string;
      /**
       * Trip Passanger Id
       * Format: uuid
       */
      trip_passanger_id: string;
      /** Trip Passanger Status */
      trip_passanger_status: string;
    };
    /**
     * TripPassangerResponse
     * @description Representação do vínculo (passageiro x trip) durante/após a execução.
     *
     *     Fields esperados:
     *     - id: UUID
     *     - route_passanger_id: UUID
     *     - passanger_name: str          — nome do usuário ou dependente
     *     - status: str                  — "pendente" | "presente" | "ausente"
     *     - pickup_address_label: str    — endereço esperado de embarque
     *     - boarded_at: datetime | None
     *     - alighted_at: datetime | None
     *     - user_phone: str              — usado pelo FE para deeplink (US13)
     *     - photo_url: str | None        — foto do usuário (FE usa nos cards de passageiro)
     */
    TripPassangerResponse: {
      /** Alighted At */
      alighted_at?: string | null;
      /** Boarded At */
      boarded_at?: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Passanger Name */
      passanger_name: string;
      /** Photo Url */
      photo_url?: string | null;
      /** Pickup Address Label */
      pickup_address_label: string;
      /**
       * Route Passanger Id
       * Format: uuid
       */
      route_passanger_id: string;
      /** Status */
      status: string;
      /** User Phone */
      user_phone: string;
    };
    /**
     * TripResponse
     * @description Representação completa da viagem em andamento.
     *
     *     Fields esperados:
     *     - id: UUID
     *     - route_id: UUID
     *     - route_name: str
     *     - vehicle_id: UUID
     *     - trip_date: datetime
     *     - status: str                  — "iniciada" | "finalizada" | "cancelada"
     *     - total_km: float | None
     *     - started_at: datetime | None
     *     - finished_at: datetime | None
     *     - trip_passangers: list[TripPassangerResponse]
     */
    TripResponse: {
      /** Finished At */
      finished_at?: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Route Id
       * Format: uuid
       */
      route_id: string;
      /** Route Name */
      route_name: string;
      /** Started At */
      started_at?: string | null;
      /** Status */
      status: string;
      /** Total Km */
      total_km?: number | null;
      /**
       * Trip Date
       * Format: date-time
       */
      trip_date: string;
      /** Trip Passangers */
      trip_passangers?: components['schemas']['TripPassangerResponse'][];
      /**
       * Vehicle Id
       * Format: uuid
       */
      vehicle_id: string;
    };
    /**
     * UpdateSchedulesRequest
     * @description Payload para o passageiro atualizar seus dias de participação.
     */
    UpdateSchedulesRequest: {
      /**
       * Schedules
       * @description Pelo menos um dia de agendamento
       */
      schedules: components['schemas']['RoutePassangerScheduleRequest'][];
    };
    /** UserCreate */
    UserCreate: {
      /**
       * Cpf
       * @example 999.999.999-99
       */
      cpf?: string | null;
      /**
       * Email
       * Format: email
       * @example john.doe@example.com
       */
      email: string;
      /**
       * Name
       * @example John Doe
       */
      name: string;
      /**
       * Password
       * @example senha_segura123
       */
      password: string;
      /**
       * Phone
       * @example 54999999999
       */
      phone: string;
      /** Photo Url */
      photo_url?: string | null;
      /**
       * Role
       * @default guardian
       */
      role: string;
    };
    /** UserResponse */
    UserResponse: {
      /** Cpf */
      cpf?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Phone */
      phone: string;
      /** Photo Url */
      photo_url?: string | null;
      /** Role */
      role: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** UserUpdate */
    UserUpdate: {
      /**
       * Cpf
       * @example 999.999.999-99
       */
      cpf?: string | null;
      /**
       * Email
       * @example john.doe@example.com
       */
      email?: string | null;
      /**
       * Name
       * @example John Doe
       */
      name?: string | null;
      /**
       * Password
       * @example senha_segura123
       */
      password?: string | null;
      /**
       * Phone
       * @example 54999999999
       */
      phone?: string | null;
      /** Photo Url */
      photo_url?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** VehicleCreate */
    VehicleCreate: {
      /** Capacity */
      capacity: number;
      /** Notes */
      notes?: string | null;
      /** Plate */
      plate: string;
    };
    /** VehicleResponse */
    VehicleResponse: {
      /** Capacity */
      capacity: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Driver Id
       * Format: uuid
       */
      driver_id: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Notes */
      notes: string | null;
      /** Plate */
      plate: string | null;
      /** Status */
      status: boolean;
    };
    /** VehicleUpdate */
    VehicleUpdate: {
      /** Capacity */
      capacity?: number | null;
      /** Notes */
      notes?: string | null;
      /** Plate */
      plate?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  read_root__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
  create_absence_absences_post: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateAbsenceRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AbsenceResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  login_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LoginResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  logout_auth_logout_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  forgot_password_auth_password_forgot_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ForgotPasswordRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  reset_password_auth_password_reset_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ResetPasswordConfirm'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  refresh_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LoginResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_dependents_dependents__get: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
        'X-User-Role': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DependentResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_dependent_dependents__post: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
        'X-User-Role': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DependentCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DependentResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_dependent_dependents__dependent_id__get: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
        'X-User-Role': string;
      };
      path: {
        dependent_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DependentResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_dependent_dependents__dependent_id__put: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
        'X-User-Role': string;
      };
      path: {
        dependent_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DependentUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DependentResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_dependent_dependents__dependent_id__delete: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
        'X-User-Role': string;
      };
      path: {
        dependent_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  health_check_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  get_reports_metrics_reports_get: {
    parameters: {
      query: {
        period: components['schemas']['ReportPeriod'];
        start_date: string;
        end_date?: string | null;
      };
      header: {
        'X-User-Id': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MetricsReportResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_routes_routes__get: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RouteResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_route_routes__post: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RouteCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RouteResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_route_by_invite_code_routes_invite__invite_code__get: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
      };
      path: {
        invite_code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RouteInviteSummaryResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_my_routes_routes_me_get: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PassangerRouteResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_route_routes__route_id__get: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
      };
      path: {
        route_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RouteResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_route_routes__route_id__put: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
      };
      path: {
        route_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RouteUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RouteResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_route_routes__route_id__delete: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
      };
      path: {
        route_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_route_absences_routes__route_id__absences_get: {
    parameters: {
      query?: {
        date?: string;
      };
      header: {
        'X-User-Id': string;
      };
      path: {
        route_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RouteAbsenceResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  regenerate_invite_code_routes__route_id__invite_code_regenerate_post: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
      };
      path: {
        route_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RouteResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_my_route_detail_routes__route_id__me_get: {
    parameters: {
      query?: {
        dependent_id?: string | null;
      };
      header: {
        'X-User-Id': string;
      };
      path: {
        route_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PassangerRouteDetailResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_passangers_routes__route_id__passangers_get: {
    parameters: {
      query?: {
        status?: string | null;
      };
      header: {
        'X-User-Id': string;
      };
      path: {
        route_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoutePassangerResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  join_route_routes__route_id__passangers_post: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
      };
      path: {
        route_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['JoinRouteRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoutePassangerResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  leave_route_routes__route_id__passangers_me_delete: {
    parameters: {
      query?: {
        dependent_id?: string | null;
      };
      header: {
        'X-User-Id': string;
      };
      path: {
        route_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_schedules_routes__route_id__passangers_me_patch: {
    parameters: {
      query?: {
        dependent_id?: string | null;
      };
      header: {
        'X-User-Id': string;
      };
      path: {
        route_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateSchedulesRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoutePassangerResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  remove_passanger_routes__route_id__passangers__rp_id__delete: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
      };
      path: {
        route_id: string;
        rp_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  accept_request_routes__route_id__passangers__rp_id__accept_post: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
      };
      path: {
        route_id: string;
        rp_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoutePassangerResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  reject_request_routes__route_id__passangers__rp_id__reject_post: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
      };
      path: {
        route_id: string;
        rp_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoutePassangerResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  start_trip_routes__route_id__trips_post: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
      };
      path: {
        route_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StartTripRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TripResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_current_trip_for_passanger_routes__route_id__trips_current_get: {
    parameters: {
      query?: {
        dependent_id?: string | null;
      };
      header: {
        'X-User-Id': string;
      };
      path: {
        route_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CurrentTripResponse'] | null;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_trip_trips__trip_id__get: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
      };
      path: {
        trip_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TripResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  finish_trip_trips__trip_id__finish_post: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
      };
      path: {
        trip_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FinishTripRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TripResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_next_stop_trips__trip_id__next_stop_get: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
      };
      path: {
        trip_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TripNextStopResponse'] | null;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  mark_passanger_absent_trips__trip_id__passangers__trip_passanger_id__absent_post: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
      };
      path: {
        trip_id: string;
        trip_passanger_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TripPassangerResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  alight_passanger_trips__trip_id__passangers__trip_passanger_id__alight_post: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
      };
      path: {
        trip_id: string;
        trip_passanger_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TripPassangerResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  board_passanger_trips__trip_id__passangers__trip_passanger_id__board_post: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
      };
      path: {
        trip_id: string;
        trip_passanger_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TripPassangerResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  skip_stop_trips__trip_id__stops__stop_id__skip_post: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
      };
      path: {
        trip_id: string;
        stop_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TripPassangerResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  upload_photo_uploads_photo_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_photo_uploads_photo_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_users_users__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'][];
        };
      };
    };
  };
  register_user_users__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  login_user_users_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_me_users_me_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_my_account_users_me_delete: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DeleteAccountRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  register_push_token_users_me_push_token_post: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterPushTokenRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  send_test_notification_users_me_send_test_notification_post: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['SendTestNotificationRequest'] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SendTestNotificationResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_user_users__user_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_user_users__user_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_user_users__user_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_vehicles_vehicles__get: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
        'X-User-Role': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VehicleResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_vehicle_vehicles__post: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
        'X-User-Role': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['VehicleCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VehicleResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_vehicle_vehicles__vehicle_id__get: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
        'X-User-Role': string;
      };
      path: {
        vehicle_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VehicleResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_vehicle_vehicles__vehicle_id__put: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
        'X-User-Role': string;
      };
      path: {
        vehicle_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['VehicleUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VehicleResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_vehicle_vehicles__vehicle_id__delete: {
    parameters: {
      query?: never;
      header: {
        'X-User-Id': string;
        'X-User-Role': string;
      };
      path: {
        vehicle_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
